language: cpp

os:
  - linux

dist: 
  - trusty

sudo: 
  - required

compiler:
  - clang

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6

env:
  - CC=clang-3.6
  - CXX=clang++-3.6

install: true

script: mkdir build && cd build && cmake .. && make && ./test/isolib_test
